spring.datasource.url=jdbc:mysql://localhost:3306/cshop?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=240405
spring.jpa.hibernate.ddl-auto=update

jwt.expiration=86400000
jwt.secret=fylsap+XXzpJAiw8ETjNg6/t6ichDXofZkLuyuS+pHw=

spring.ai.vectorstore.qdrant.host=${QDRANT_HOST}
spring.ai.vectorstore.qdrant.port=6333
spring.ai.vectorstore.qdrant.use-tls=true
spring.ai.vectorstore.qdrant.api-key=${QDRANT_API_KEY}

spring.ai.vectorstore.qdrant.collection-name=pc_products
spring.ai.vectorstore.qdrant.initialize-schema=true
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.project-id=default
spring.ai.google.genai.location=us-central1
spring.ai.google.genai.chat.options.model=gemini-3.6-flash
spring.ai.google.genai.embedding.text.options.model=gemini-embedding-001

