spring.datasource.url=jdbc:mysql://localhost:3306/cshop 
spring.datasource.username=root
spring.datasource.password=240405
spring.jpa.hibernate.ddl-auto=update

jwt.expiration=86400000
jwt.secret=fylsap+XXzpJAiw8ETjNg6/t6ichDXofZkLuyuS+pHw=